# Generated by Django 4.2.2 on 2023-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='sentiment',
            field=models.CharField(max_length=10),
        ),
    ]
